# Generated by Django 5.0.2 on 2024-02-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_alter_membership_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment_type',
            field=models.CharField(choices=[('Zelle', 'Zelle'), ('Paypal', 'Paypal'), ('Cash App', 'Cash App'), ('Bank Transfer', 'Bank Transfer'), ('Cash Mailing', 'Cash Mailing'), ('Crypto', 'Crypto')], max_length=50),
        ),
    ]
