# Generated by Django 5.0.2 on 2024-03-02 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_alter_membership_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('preferred_dates', models.DateField()),
                ('preferred_payment_method', models.CharField(choices=[('Zelle', 'Zelle'), ('Paypal', 'Paypal'), ('Cash App', 'Cash App'), ('Bank Transfer', 'Bank Transfer'), ('Cash Mailing', 'Cash Mailing'), ('Crypto', 'Crypto')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autographs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autograph',
                'verbose_name_plural': 'Autographs',
            },
        ),
        migrations.CreateModel(
            name='GeneralMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('Zelle', 'Zelle'), ('Paypal', 'Paypal'), ('Cash App', 'Cash App'), ('Bank Transfer', 'Bank Transfer'), ('Cash Mailing', 'Cash Mailing'), ('Crypto', 'Crypto')], max_length=50)),
                ('country', models.CharField(default='test country', max_length=100)),
                ('state', models.CharField(default='test state', max_length=100)),
                ('city', models.CharField(default='test city', max_length=100)),
                ('address', models.TextField(default='test address')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.membershiptype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Membership',
                'verbose_name_plural': 'General Memberships',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('preferred_destination', models.CharField(max_length=255)),
                ('favourite_artist_band', models.CharField(max_length=255)),
                ('benefit_card_copy', models.ImageField(blank=True, null=True, upload_to='benefit_card_copies/')),
                ('preferred_dates', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('special_requests', models.TextField()),
                ('select_week', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('preferred_payment_method', models.CharField(choices=[('Zelle', 'Zelle'), ('Paypal', 'Paypal'), ('Cash App', 'Cash App'), ('Bank Transfer', 'Bank Transfer'), ('Cash Mailing', 'Cash Mailing'), ('Crypto', 'Crypto')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
    ]
