"""
Django settings for main_p project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import cloudinary
import cloudinary_storage
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q6eau(qpq2bmkqcyv_f4%%!$btq-_j@nsra$l-30iog&8=j2qq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'home',
    'accounts',
    'band',
    'email_app',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main_p.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_p.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'livesmis_db',
#         'USER': 'livesmis_user',
#         'PASSWORD': 'Live@#123456789',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }}

# main_p/settings.py
AUTH_USER_MODEL = 'accounts.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Define the root directory for static files.
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/root')

# Define the directory where your static files are located.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Define the root directory for media files.
MEDIA_URL = '/LiveNationGlobal_image_media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'ddirw9v0d',
    'API_KEY': '736136276635934',
    'API_SECRET': '8ePybnqjE4xP9HlGMhT_jyUiiTI'
}

CKEDITOR_BASEPATH = "/static/root/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = 'uploads/'  
CKEDITOR_IMAGE_BACKEND = "ckeditor_uploader.backends.PillowBackend"

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_JQUERY_URL = 'https://code.jquery.com/jquery-3.6.0.min.js'  # Use the appropriate jQuery version
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}
# CKEditor jQuery URL
CKEDITOR_JQUERY_URL = 'https://code.jquery.com/jquery-3.6.0.min.js'

# CKEditor Uploader settings
CKEDITOR_ALLOW_NONIMAGE_FILES = True  # Disallow non-image file uploads (can be True if needed).
CKEDITOR_RESTRICT_BY_USER = True  # Restrict file uploads to the current user.
CKEDITOR_FILENAME_GENERATOR = 'ckeditor_uploader.utils.get_filename'

# CKEditor Uploader views (optional, for more advanced usage)
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_BROWSE_SHOW_HIDDEN = False
CKEDITOR_BROWSE_SHOW_INFO = True

# CKEditor media settings
CKEDITOR_MEDIA_PREFIX = '/resource/media/ckeditor/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'osender6@gmail.com'
EMAIL_HOST_PASSWORD = 'zfhmpxnlckhzjfeg'
EMAIL_USE_SSL = False

# Additional settings for Gmail
# DEFAULT_FROM_EMAIL = 'your-email@gmail.com'  # Set your default 'from' email address
# SERVER_EMAIL = 'your-email@gmail.com'  # Set your server email address

# Set the email timeout (optional)
EMAIL_TIMEOUT = 100  # seconds